server:
  port: 8181
spring:
  datasource:
    url: jdbc:mysql://10.237.161.213:3306/demo
    username: user_dev
    password: Zaq_2wsx
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapping/*.xml #????????mapper??xml???????
  type-aliases-package: com.moerlong.yj.model # ???????????
